spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #doing this for testing only TODO: change to validate in after testing in prod is done
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  cloud:
    azure:
      storage:
        blob:
          container-name: ${STORAGE_CONTAINER_NAME}
          account-name: ${STORAGE_ACCOUNT_NAME}
          account-key: ${STORAGE_ACCOUNT_KEY}

jwt:
  secret: ${JWT_SECRET:}
  access-token-expiry: ${ACCESS_TOKEN_EXPIRY}
  refresh-token-expiry: ${REFRESH_TOKEN_EXPIRY}
app:
  name: nhx
  support-email: ${SUPPORT_EMAIL:}
  base-url: ${BASE_URL:}

admin:
  notification:
    email: ${ADMIN_NOTIFICATION_EMAIL:}

multisig:
  api:
    url: ${MULTISIG_API_URL}
  account-id: ${ACCOUNT_ID}
  network: ${MULTISIG_NETWORK}
  key-list:
    - ${PUBLIC_KEY}
    - ${PUBLIC_KEY2}
    - ${PUBLIC_KEY3}

sdk:
  url: ${SDK_URL}
  sdk-api-key: ${SDK_API_KEY}

resilience4j:
  retry:
    instances:
      sdkApi:
        max-attempts: 3
        wait-duration: 1000
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.net.SocketTimeoutException
        ignore-exceptions:
          - com.javaguy.nhx.exception.custom.BadRequestException
  circuitbreaker:
    instances:
      sdkApi:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 40000
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30000
        permitted-number-of-calls-in-half-open-state: 3
