spring:
  application:
    name: nhx-kesy-platform
  profiles:
    active: prod

logging:
  level:
    root: ERROR
    com.javaguy.nhx: WARN
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/nhx.log
    max-size: 10MB
    max-history: 30
